apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bxfg5jtaq-python 
  janus-idp.io/tekton: bxfg5jtaq-python
  backstage.io/kubernetes-id: bxfg5jtaq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bxfg5jtaq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  