apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bxfg5jtaq-python-gitops
  description: This is GitOps manifest for bxfg5jtaq-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bxfg5jtaq-python
    backstage.io/kubernetes-id: bxfg5jtaq-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bxfg5jtaq-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bxfg5jtaq-python
